ifndef::imagesdir[:imagesdir: ../images]

[[section-system-scope-and-context]]
== System Scope and Context


[role="arc42help"]
****
.Contents
System scope and context - as the name suggests - delimits your system (i.e. your scope) from all its communication partners
(neighboring systems and users, i.e. the context of your system). It thereby specifies the external interfaces.

If necessary, differentiate the business context (domain specific inputs and outputs) from the technical context (channels, protocols, hardware).

.Motivation
The domain interfaces and technical interfaces to communication partners are among your system's most critical aspects. Make sure that you completely understand them.

.Form
Various options:

* Context diagrams
* Lists of communication partners and their interfaces.


.Further Information

See https://docs.arc42.org/section-3/[Context and Scope] in the arc42 documentation.

****


=== Business Context

[role="arc42help"]
****
.Contents
Specification of *all* communication partners (users, IT-systems, ...) with explanations of domain specific inputs and outputs or interfaces.
Optionally you can add domain specific formats or communication protocols.

.Motivation
All stakeholders should understand which data are exchanged with the environment of the system.

.Form
All kinds of diagrams that show the system as a black box and specify the domain interfaces to communication partners.

Alternatively (or additionally) you can use a table.
The title of the table is the name of your system, the three columns contain the name of the communication partner, the inputs, and the outputs.

****

The player is the only actor in the main system, which is the one that makes use of the different APIs that will be described later.
The player can initially interact with the authentication system to either register or login and then, by playing the game, the question
service will be triggered for either generating the questions or validating the player's answer. The player can also access data about 
the past games of all users in a ranking.

[plantuml,"Context Diagram",png]
----
actor Player
[Wikidata] <<external>>
database MongoDB

[WIQ Game] <<system>>
[UsersAPI] <<internal>>
[QuestionsAPI] <<internal>>
Player ..> (WIQ Game) : register/login
[QuestionsAPI] ..> Wikidata
[WIQ Game] ..> UsersAPI
[WIQ Game] ..> QuestionsAPI
[UsersAPI] <--> MongoDB
[QuestionsAPI] ..> UsersAPI
----

[cols="e,2e" options="header"]
|===
|Element |Description

|Player
|Plays the game and can consult past scores

|WIQ Game
|Main system in which generated questions are shown and can be answered by players

|Wikidata
|External data repository from which questions are generated

|Users Info API
|Manages data of users, both registration/login data and their past scores

|Questions API
|Manages generation of questions from Wikidata

|MongoDB
|Database for storing players' info and scores
|===