ifndef::imagesdir[:imagesdir: ../images]

[[section-system-scope-and-context]]
== System Scope and Context


[role="arc42help"]
****
.Contents
System scope and context - as the name suggests - delimits your system (i.e. your scope) from all its communication partners
(neighboring systems and users, i.e. the context of your system). It thereby specifies the external interfaces.

If necessary, differentiate the business context (domain specific inputs and outputs) from the technical context (channels, protocols, hardware).

.Motivation
The domain interfaces and technical interfaces to communication partners are among your system's most critical aspects. Make sure that you completely understand them.

.Form
Various options:

* Context diagrams
* Lists of communication partners and their interfaces.


.Further Information

See https://docs.arc42.org/section-3/[Context and Scope] in the arc42 documentation.

****


=== Business Context

[role="arc42help"]
****
.Contents
Specification of *all* communication partners (users, IT-systems, ...) with explanations of domain specific inputs and outputs or interfaces.
Optionally you can add domain specific formats or communication protocols.

.Motivation
All stakeholders should understand which data are exchanged with the environment of the system.

.Form
All kinds of diagrams that show the system as a black box and specify the domain interfaces to communication partners.

Alternatively (or additionally) you can use a table.
The title of the table is the name of your system, the three columns contain the name of the communication partner, the inputs, and the outputs.

****

[plantuml,"Context diagram",png]
----
actor Player
actor Client
database MongoDB <<local>>
[WIQ Game] <<system>>
[Wikidata] <<external>>
[UsersInfoAPI] <<internal>>
[GeneratedQuestionsAPI] <<internal>>
Player .> (WIQ Game) : login
Client ..> (UsersInfoAPI)
Client ..> (GeneratedQuestionsAPI)
MongoDB --> (UsersInfoAPI)
MongoDB --> (GeneratedQuestionsAPI)
[WIQ Game] <.> (Wikidata) : WikidataAPI
[WIQ Game] <--> (MongoDB)
----

[cols="e,2e" options="header"]
|===
|Element |Description

|Player
|Plays the game and can consult past scores

|Client
|Can access the data about players and generated questions

|WIQ Game
|Main system in which generated questions are shown and can be answered by players

|Wikidata
|External data repository from which questions are generated using the WikidataAPI

|MongoDB
|Database for storing generated questions, players' info and scores

|Users Info API
|Allows clients to see the info about players stored in the database

|Generated Questions API
|Allows clients to see the info about generated questions stored in the database
|===