ifndef::imagesdir[:imagesdir: ../images]

[[section-runtime-view]]
== Runtime View
=== User authentication
* Users will log in through the web interface of the application.
* The system stores in database (MongoDB) the users of the application. Any data relative to them is accessed via the database of the system and displayed to them on the web interface.

=== Rankings
* Users can see the rankings for a specific category

[plantuml,"rankings_diagram",png]
----
entity User
entity WEBC as "Web Client"
entity GW as "Gateway"
entity USERS as "Users service"
database DB as "MongoDB"

User -> WEBC: Navigate to rankings page
WEBC -> GW: Get global statistics
GW -> USERS: Get global statistics
USERS -> DB: Get statistics matching the specified category
USERS -> GW: Send global statistics
GW -> WEBC: Send global statistics
User -> WEBC: Select a category
WEBC -> GW: Get category statistics
GW -> USERS: Get category statistics
USERS -> DB: Get statistics matching the specified category
USERS -> GW: Send category statistics
GW -> WEBC: Send category statistics
----

=== Playing
* An overview of the runtime scenario of a game.

[plantuml, "playing_diagram", png]
----
actor User
entity WEBC as "Web Client"
entity GW as "Gateway"
database DB as "MongoDB"
entity QU as "Questions API"
entity USERS as "Users Service API"

User -> WEBC: Select a category to play
WEBC -> GW: Get a question
GW -> QU: Get a question
QU -> QU: Store question and answer
QU -> GW: Send question to client
GW -> WEBC: Send question to client
User -> WEBC: Answer question
WEBC -> GW: Send answer
GW -> QU: Send answer
QU -> QU: Check answer
QU -> USERS: Update user points
USERS -> DB: Modify user data
QU -> GW: Send result and new question
GW -> WEBC: Send result and new question
----

[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...


.Further Information

See https://docs.arc42.org/section-6/[Runtime View] in the arc42 documentation.

****
