ifndef::imagesdir[:imagesdir: ../images]

[[section-deployment-view]]


== Deployment View

[role="arc42help"]
****
.Content
The deployment view describes:

 1. technical infrastructure used to execute your system, with infrastructure elements like geographical locations, environments, computers, processors, channels and net topologies as well as other infrastructure elements and

2. mapping of (software) building blocks to that infrastructure elements.

Often systems are executed in different environments, e.g. development environment, test environment, production environment. In such cases you should document all relevant environments.

Especially document a deployment view if your software is executed as distributed system with more than one computer, processor, server or container or when you design and construct your own hardware processors and chips.

From a software perspective it is sufficient to capture only those elements of an infrastructure that are needed to show a deployment of your building blocks. Hardware architects can go beyond that and describe an infrastructure to any level of detail they need to capture.

.Motivation
Software does not run without hardware.
This underlying infrastructure can and will influence a system and/or some
cross-cutting concepts. Therefore, there is a need to know the infrastructure.

.Form

Maybe a highest level deployment diagram is already contained in section 3.2. as
technical context with your own infrastructure as ONE black box. In this section one can
zoom into this black box using additional deployment diagrams:

* UML offers deployment diagrams to express that view. Use it, probably with nested diagrams,
when your infrastructure is more complex.
* When your (hardware) stakeholders prefer other kinds of diagrams rather than a deployment diagram, let them use any kind that is able to show nodes and channels of the infrastructure.


.Further Information

See https://docs.arc42.org/section-7/[Deployment View] in the arc42 documentation.

****

=== Infrastructure Level 1
An overall of the infrastructure elements used to execute the system can be seen in the following diagram.
[plantuml,"Deployment view L1",png]
----
node "User Computer" {
  component WC as "Web Client"
}

node "WIQ Server"{
  component GS as "Gateway Service"
  component WA as "Web Application"
}

node "Wikidata Server"{
  component WAPI as "Wikidata API"
}


GS-[dashed]->WAPI
WA-[dashed]->GS
WC-[dashed]->WA
WA-[dashed]->WC
WC-[dashed]->GS
----
[role="arc42help"]
****
Describe (usually in a combination of diagrams, tables, and text):

* distribution of a system to multiple locations, environments, computers, processors, .., as well as physical connections between them
* important justifications or motivations for this deployment structure
* quality and/or performance features of this infrastructure
* mapping of software artifacts to elements of this infrastructure

For multiple environments or alternative deployments please copy and adapt this section of arc42 for all relevant environments.
****
The gateway service works as an adapter between the micro services and the web client. The web application is the main interface for the user to interact with the system. The wikidata API is used to fetch data from wikidata to generate questions. We must consider the gateway service a black box.


=== Infrastructure Level 2

[role="arc42help"]
****
Here you can include the internal structure of (some) infrastructure elements from level 1.

Please copy the structure from level 1 for each selected element.
****

==== _WIQ Server_
[plantuml,"Deployment view L2",png]
----
node "WIQ Server"{
  component GS as "Gateway Service"
  component WA as "Web Application"
  component US as "User Service"
  component AS as "Authorization Service"
  component QS as "Question Service"
  database MDB as "Mongo DB"
}




GS-[dashed]->WA
WA-[dashed]->GS

GS-[dashed]->AS
AS-[dashed]->GS

GS-[dashed]->US
US-[dashed]->GS

GS-[dashed]->QS
QS-[dashed]->GS

AS-[dashed]->MDB
MDB-[dashed]->AS

US-[dashed]->MDB
MDB-[dashed]->US

QS-[dashed]->MDB
MDB-[dashed]->QS
----
The architecture of WIQ is based on microservices. Gateway service is the main entry point for the system. The web application is the main interface for the user to interact with the system. The user service is responsible for managing users. The authorization service is responsible for managing user permissions. The question service is responsible for generating questions. The mongo database is used to store data.


